### ISSUE TITLE
Support DLL load/unload events

### ISSUE THREAD

**Issue by mrexodia** [x64dbg/DotX64Dbg#82]

**Comment by xorhex** [comment]
:eyes:  Sounds like this might answer my question. Was going to ask "How to resolve a memory location to the module name?".  Have a dll base address and trying to get the corresponding dll name.

**Comment by mrexodia** [comment]
I think you can do that already. The most hacky way I can think of now is to evaluate an expression “module:0” and that will give you the base.

This issue specifically is about the load events from the debug api, which are currently missing.
