### ISSUE TITLE
Setup - Missing Dependancies

### ISSUE THREAD

**Issue by xorhex** [x64dbg/DotX64Dbg#84]
Excited about this project.

Installed both of the requirements linked to in the log, but still getting this error message.

```
Unable to load Dotx64Dbg, make sure you have following installed:
- .NET 6.0 Runtime (https://dotnet.microsoft.com/download/dotnet/6.0)
- Visual Studio 2019 Runtime (https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0)
```

I've also clone the repo and was able to successfully build it.

Both x86 and x64
![Screenshot from 2023-03-10 17-56-02](https://user-images.githubusercontent.com/40742023/224443533-14e963c5-2c43-491e-9d7c-6ef22a497d3b.png)
![Screenshot from 2023-03-10 17-55-22](https://user-images.githubusercontent.com/40742023/224443534-ea9e4eb5-acfa-4882-8d76-dd1f1b962495.png)

Running x64dbg version snapshot_2023-03-04_02-26  

Here is my placement of the plugin files:

![Screenshot from 2023-03-10 17-51-39](https://user-images.githubusercontent.com/40742023/224443067-20f6c76c-1d7c-4589-930d-20f85e5a8dad.png)
![Screenshot from 2023-03-10 17-51-26](https://user-images.githubusercontent.com/40742023/224443072-02a62c7a-fb06-438c-9c18-19bfae41f35b.png)

Am I missing something?

**Comment by mrexodia** [comment]
Can you check procmon?

**Comment by xorhex** [comment]
Thanks, I had to add `Ijwhost.dll` to the `snapshot/release/x64/` folder for the Dotx64dbg.dll to load.

**Comment by snq-** [comment]
Thank you for investigating the issue. Currently it affects all plugins with library dependencies that are not available in the app folder (x32/x64) or under system32. 

Adding the 'plugins' directory to LOAD_LIBRARY_SEARCH_USER_DIRS surely helps in case of dotx64dbg, but still requires one to put all the dependencies in one single folder.

(In the meantime I have [moved the reset code](https://github.com/snq-/x64dbg/commit/239b95d3c8c0d3c76bd7a4c5ce505e3be16edc6b) from /exe to /dbg as per you advice. Also [added the plugins folder](https://github.com/snq-/x64dbg/commit/16cfe9aeb3371587d53c0d8b1b3fdd7a0dc22ecd) to the list there.)

**Comment by mrexodia** [comment]
Just wanted to give a heads-up, this was fixed in the latest x64dbg snapshot. `Ijwhost.dll` can now be placed next to Dotx64dbg.dll as normal.
