### ISSUE TITLE
Dependencies are not loaded

### ISSUE THREAD

**Issue by BadRyuner** [x64dbg/DotX64Dbg#87]
When I use the command the first time I run x64dbg, I get an error:
```
Exception: System.MissingMethodException: Method not found: 'System.Collections.Immutable.ImmutableArray`1<Microsoft.Diagnostics.Runtime.ClrInfo> Microsoft.Diagnostics.Runtime.DataTarget.get_ClrVersions()'. 
   at DotInfo.Plugin.Init(String[] args) 
   at Dotx64Dbg.Plugins.<>c__DisplayClass44_0.<RegisterPluginCommand>b__0(String[] args) 
   at Dotx64Dbg.Commands.CommandHandler(String cmd, Int32 argc, IntPtr ptr) 
   at Dotx64Dbg.Commands.<>c__DisplayClass8_0.<Register>b__0(Int32 argc, IntPtr argv)
```
The error disappears if you add a couple of spaces in the source code to run hotreload.
After reloading x64dbg, the error reappears until you run hotreload through adding spaces...
P.S "Microsoft.Diagnostics.Runtime.DataTarget.get_ClrVersions" is a method from the nuget package.

**Comment by mrexodia** [comment]
Can you post a standalone plugin source that triggers this issue?

**Comment by BadRyuner** [comment]
Sure, https://github.com/BadRyuner/DotInfo

**Comment by ZehMatt** [comment]
I'm having trouble reproducing the issue, could you provide some detailed steps to how to get this error?

**Comment by BadRyuner** [comment]
1) Add any plugin, which uses nuget package.
2) Try run any command, which calls anything from this nuget package.
3) Get the error "MissingMethodException"
4) Add some spaces to any source file and trigger HotReload.
5) Run again this command and the error disappear
6) PROFIT

...) After restarting x64dbg, repeat the steps again.

On first plugin load, required nuget dlls are not loaded.
On second load (after hotreload), required nuget dlls are loaded.
Why? idk

**Comment by Guila767** [comment]
Sorry, I only saw this post today. I took a brief look at this and it appears to be a problem with a mismatched version of the System.Collections.Immutable library. Your plugin uses a Nuget library that internally requires a specific version of the 'System.Collections.Immutable'. What is likely happening is that another version of the same library is already loaded at the current assembly domain. When your plugin gets loaded is trying to use a version that doesn't contain the method implementation needed.

Looking at the loaded modules in x64Dbg, we can see two libraries loaded. The one, with the lowest base address, is the one loaded by our Nuget dependency handling. The other one is likely a kernel-loaded module and is shared across another process.

![Screenshot 2023-07-15 170708](https://github.com/x64dbg/DotX64Dbg/assets/31376051/40fd7cbe-2731-4012-acb4-66fac571e0b1)

Of course, this is not your fault and is something that I may have overlooked when I did the NuGet contribution

**Comment by Guila767** [comment]
Currently, I'm investigating why this can happen at the plugin's first startup. I believe a temporary solution is to trigger a hot reload in your plugin or reload XDot64Dbg with `reloadplugin DotX64Dbg.Loader` command (maybe is not recommended, idk)

**Comment by ZehMatt** [comment]
> Currently, I'm investigating why this can happen at the plugin's first startup. I believe a temporary workaround is to trigger a hot reload in your plugin or reload XDot64Dbg with `reloadplugin DotX64Dbg.Loader` command (maybe is not recommended, idk)

Thanks for looking into this, I came to the same conclusion as your comment before but I'm not really sure on what to do about it, for some reason it loads the dll twice once from nuget the other time its the system wide installed version, and as to why it works after a hot-load is a bit beyond me to be honest.
