### ISSUE TITLE
Software crashes after installing plugin on 32-bit version"

### ISSUE THREAD

**Issue by mounirthabet** [x64dbg/DotX64Dbg#91]
I am encountering issues with this plugin that is designed for 32-bit, while running it on Windows 11, snapshot_2023-09-16_13-36. x64dbg keeps crashing upon launch. I require immediate assistance to resolve this problem.

**Comment by mrexodia** [comment]
I really need a million dollars.

**Comment by mounirthabet** [comment]
sorry if not the best way to ask for help but I waste 3days trying to fix this thanks anyways

**Comment by ZehMatt** [comment]
Have you installed the .NET 5.0 redistributables for 32 bit? Without any more details there is little we can do, I can not reproduce this on my end.

**Comment by mounirthabet** [comment]
thank you so much After I installed this version of SDK x64dbg was able to launch correctly :
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.100-windows-x86-installer
